const toolsData = [
    // ===== IMAGE TOOLS =====
    { id: 'image-compressor', name: 'Image Compressor', slug: 'image-compressor', category: 'image-tools', categoryName: 'Image Tools', icon: '🖼️', description: 'Compress images without losing quality. Reduce file size for faster loading.', keywords: ['compress', 'reduce', 'optimize', 'image'] },
    { id: 'image-resizer', name: 'Image Resizer', slug: 'image-resizer', category: 'image-tools', categoryName: 'Image Tools', icon: '📐', description: 'Resize images to any dimension. Perfect for social media and web use.', keywords: ['resize', 'dimension', 'scale', 'image'] },
    { id: 'jpg-to-png', name: 'JPG to PNG Converter', slug: 'jpg-to-png', category: 'image-tools', categoryName: 'Image Tools', icon: '🔄', description: 'Convert JPG images to PNG format with transparency support.', keywords: ['jpg', 'png', 'convert', 'image'] },
    { id: 'png-to-jpg', name: 'PNG to JPG Converter', slug: 'png-to-jpg', category: 'image-tools', categoryName: 'Image Tools', icon: '🔄', description: 'Convert PNG images to JPG format for smaller file sizes.', keywords: ['png', 'jpg', 'convert', 'image'] },
    { id: 'image-crop', name: 'Image Crop Tool', slug: 'image-crop', category: 'image-tools', categoryName: 'Image Tools', icon: '✂️', description: 'Crop images to any size or aspect ratio with precision controls.', keywords: ['crop', 'cut', 'trim', 'image'] },
    { id: 'image-to-base64', name: 'Image to Base64', slug: 'image-to-base64', category: 'image-tools', categoryName: 'Image Tools', icon: '🔣', description: 'Convert images to Base64 encoded strings for embedding in code.', keywords: ['base64', 'encode', 'embed', 'image'] },
    { id: 'screenshot-tool', name: 'Screenshot Tool', slug: 'screenshot-tool', category: 'image-tools', categoryName: 'Image Tools', icon: '📸', description: 'Take screenshots of any screen or window. Download as PNG/JPG or copy to clipboard.', keywords: ['screenshot', 'capture', 'screen', 'snapshot', 'image'] },
    { id: 'image-format-converter', name: 'Image Format Converter', slug: 'image-format-converter', category: 'image-tools', categoryName: 'Image Tools', icon: '🔄', description: 'Convert images between JPG, PNG, WebP, GIF, BMP, TIFF, and ICO formats. Free batch conversion.', keywords: ['convert', 'image', 'jpg', 'png', 'webp', 'gif', 'format'] },
    { id: 'image-filter-editor', name: 'Image Filter Editor', slug: 'image-filter-editor', category: 'image-tools', categoryName: 'Image Tools', icon: '🎨', description: 'Apply professional filters to images. Adjust brightness, contrast, saturation, and more.', keywords: ['filter', 'edit', 'brightness', 'contrast', 'photo', 'effects'] },
    { id: 'image-watermark', name: 'Image Watermark Adder', slug: 'image-watermark', category: 'image-tools', categoryName: 'Image Tools', icon: '💧', description: 'Add text or image watermarks to photos. Customize position, opacity, and style.', keywords: ['watermark', 'copyright', 'logo', 'text', 'protect', 'image'] },
    { id: 'avif-to-jpg-converter', name: 'AVIF to JPG Converter', slug: 'avif-to-jpg-converter', category: 'image-tools', categoryName: 'Image Tools', icon: '🖼️', description: 'Convert AVIF images to JPG format for better compatibility. Fast and high quality.', keywords: ['avif', 'jpg', 'convert', 'image', 'format'] },

    // ===== PDF TOOLS =====
    { id: 'merge-pdf', name: 'Merge PDF', slug: 'merge-pdf', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '📑', description: 'Combine multiple PDF files into a single document instantly.', keywords: ['merge', 'combine', 'join', 'pdf'] },
    { id: 'split-pdf', name: 'Split PDF', slug: 'split-pdf', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '✂️', description: 'Split a PDF file into multiple separate documents by page range.', keywords: ['split', 'separate', 'divide', 'pdf'] },
    { id: 'compress-pdf', name: 'Compress PDF', slug: 'compress-pdf', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '📦', description: 'Reduce PDF file size while maintaining quality for easy sharing.', keywords: ['compress', 'reduce', 'shrink', 'pdf'] },
    { id: 'pdf-to-image', name: 'PDF to Image', slug: 'pdf-to-image', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '🖼️', description: 'Convert PDF pages to high-quality PNG or JPG images.', keywords: ['pdf', 'image', 'convert', 'png', 'jpg'] },
    { id: 'pdf-page-extractor', name: 'PDF Page Extractor', slug: 'pdf-page-extractor', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '📄', description: 'Extract specific pages from a PDF document.', keywords: ['extract', 'page', 'remove', 'pdf'] },
    { id: 'pdf-preview', name: 'PDF Preview', slug: 'pdf-preview', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '👁️', description: 'Preview PDF files directly in your browser without downloading.', keywords: ['preview', 'view', 'read', 'pdf'] },
    { id: 'pdf-to-word', name: 'PDF to Word Converter', slug: 'pdf-to-word', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '📝', description: 'Convert PDF files to editable Word documents. Free online PDF to DOC converter.', keywords: ['pdf', 'word', 'convert', 'doc', 'editable'] },
    { id: 'word-to-pdf', name: 'Word to PDF Converter', slug: 'word-to-pdf', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '📄', description: 'Convert Word documents (.doc, .docx) to PDF format. Free and secure conversion.', keywords: ['word', 'pdf', 'convert', 'doc', 'docx'] },
    { id: 'pdf-to-excel', name: 'PDF to Excel Converter', slug: 'pdf-to-excel', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '📊', description: 'Extract tables from PDF to Excel format. Convert PDF data to CSV spreadsheets.', keywords: ['pdf', 'excel', 'convert', 'csv', 'table'] },
    { id: 'rotate-pdf', name: 'Rotate PDF', slug: 'rotate-pdf', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '🔄', description: 'Rotate PDF pages by 90°, 180°, or 270°. Fix orientation of scanned documents.', keywords: ['rotate', 'pdf', 'orientation', 'pages'] },
    { id: 'add-page-numbers-to-pdf', name: 'Add Page Numbers to PDF', slug: 'add-page-numbers-to-pdf', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '🔢', description: 'Add custom page numbers to PDF documents. Choose position, format, and starting number.', keywords: ['page numbers', 'pdf', 'numbering', 'paginate'] },
    { id: 'compress-pdf-pages', name: 'Compress PDF Pages', slug: 'compress-pdf-pages', category: 'pdf-tools', categoryName: 'PDF Tools', icon: '🗜️', description: 'Optimize and compress PDF files by reducing page size. Make PDFs smaller for sharing.', keywords: ['compress', 'optimize', 'pdf', 'reduce', 'shrink'] },

    // ===== DEVELOPER TOOLS =====
    { id: 'json-formatter', name: 'JSON Formatter', slug: 'json-formatter', category: 'developer-tools', categoryName: 'Developer Tools', icon: '{ }', description: 'Format, validate, and beautify JSON data with syntax highlighting.', keywords: ['json', 'format', 'validate', 'beautify'] },
    { id: 'base64-encoder-decoder', name: 'Base64 Encoder/Decoder', slug: 'base64-encoder-decoder', category: 'developer-tools', categoryName: 'Developer Tools', icon: '🔐', description: 'Encode text to Base64 or decode Base64 strings instantly.', keywords: ['base64', 'encode', 'decode', 'convert'] },
    { id: 'jwt-decoder', name: 'JWT Decoder', slug: 'jwt-decoder', category: 'developer-tools', categoryName: 'Developer Tools', icon: '🔑', description: 'Decode and inspect JSON Web Tokens (JWT) header and payload.', keywords: ['jwt', 'token', 'decode', 'json'] },
    { id: 'regex-tester', name: 'Regex Tester', slug: 'regex-tester', category: 'developer-tools', categoryName: 'Developer Tools', icon: '🔍', description: 'Test and debug regular expressions with real-time matching.', keywords: ['regex', 'regular expression', 'test', 'match'] },
    { id: 'code-beautifier', name: 'Code Beautifier', slug: 'code-beautifier', category: 'developer-tools', categoryName: 'Developer Tools', icon: '✨', description: 'Beautify and format HTML, CSS, and JavaScript code instantly.', keywords: ['beautify', 'format', 'html', 'css', 'javascript'] },
    { id: 'css-js-minifier', name: 'CSS & JS Minifier', slug: 'css-js-minifier', category: 'developer-tools', categoryName: 'Developer Tools', icon: '🗜️', description: 'Minify CSS and JavaScript code to reduce file size.', keywords: ['minify', 'compress', 'css', 'javascript'] },
    { id: 'qr-code-generator', name: 'QR Code Generator', slug: 'qr-code-generator', category: 'developer-tools', categoryName: 'Developer Tools', icon: '🔲', description: 'Generate custom QR codes for URLs, text, email, phone numbers, and WiFi. Free download as PNG.', keywords: ['qr', 'code', 'generator', 'barcode', 'scan'] },
    { id: 'color-picker', name: 'Color Picker', slug: 'color-picker', category: 'developer-tools', categoryName: 'Developer Tools', icon: '🎨', description: 'Pick colors and convert between HEX, RGB, and HSL formats. Includes color palette and CSS export.', keywords: ['color', 'picker', 'hex', 'rgb', 'hsl', 'converter'] },
    { id: 'markdown-editor', name: 'Markdown Editor', slug: 'markdown-editor', category: 'developer-tools', categoryName: 'Developer Tools', icon: '📝', description: 'Write and preview Markdown with live preview. Export to HTML. Perfect for documentation.', keywords: ['markdown', 'editor', 'md', 'html', 'preview'] },
    { id: 'diff-checker', name: 'Diff Checker', slug: 'diff-checker', category: 'developer-tools', categoryName: 'Developer Tools', icon: '📊', description: 'Compare two texts and highlight differences. Find changes between code, documents, or any text.', keywords: ['diff', 'compare', 'difference', 'checker', 'text'] },
    { id: 'unix-timestamp-converter', name: 'Unix Timestamp Converter', slug: 'unix-timestamp-converter', category: 'developer-tools', categoryName: 'Developer Tools', icon: '⏱️', description: 'Convert Unix timestamps to human-readable dates and vice versa. Live current timestamp display.', keywords: ['unix', 'timestamp', 'epoch', 'converter', 'date'] },
    { id: 'html-entity-encoder', name: 'HTML Entity Encoder/Decoder', slug: 'html-entity-encoder', category: 'developer-tools', categoryName: 'Developer Tools', icon: '🔣', description: 'Encode special characters to HTML entities and decode them back. Prevent XSS attacks.', keywords: ['html', 'entity', 'encode', 'decode', 'escape'] },
    { id: 'user-agent-parser', name: 'User Agent Parser', slug: 'user-agent-parser', category: 'developer-tools', categoryName: 'Developer Tools', icon: '🌐', description: 'Parse and analyze browser user agent strings. Detect browser, OS, device, and engine.', keywords: ['user agent', 'parser', 'browser', 'os', 'device'] },

    // ===== TEXT TOOLS =====
    { id: 'word-counter', name: 'Word Counter', slug: 'word-counter', category: 'text-tools', categoryName: 'Text Tools', icon: '📝', description: 'Count words, characters, sentences, and paragraphs in your text.', keywords: ['word', 'count', 'character', 'text'] },
    { id: 'text-case-converter', name: 'Text Case Converter', slug: 'text-case-converter', category: 'text-tools', categoryName: 'Text Tools', icon: 'Aa', description: 'Convert text between uppercase, lowercase, title case, and more.', keywords: ['case', 'convert', 'uppercase', 'lowercase'] },
    { id: 'slug-generator', name: 'Slug Generator', slug: 'slug-generator', category: 'text-tools', categoryName: 'Text Tools', icon: '🔗', description: 'Generate URL-friendly slugs from any text for SEO-friendly URLs.', keywords: ['slug', 'url', 'seo', 'generate'] },
    { id: 'meta-tag-generator', name: 'Meta Tag Generator', slug: 'meta-tag-generator', category: 'text-tools', categoryName: 'Text Tools', icon: '🏷️', description: 'Generate HTML meta tags for SEO optimization of your website.', keywords: ['meta', 'tag', 'seo', 'html'] },
    { id: 'url-encoder-decoder', name: 'URL Encoder/Decoder', slug: 'url-encoder-decoder', category: 'text-tools', categoryName: 'Text Tools', icon: '🌐', description: 'Encode or decode URLs and query parameters instantly.', keywords: ['url', 'encode', 'decode', 'query'] },
    { id: 'lorem-ipsum-generator', name: 'Lorem Ipsum Generator', slug: 'lorem-ipsum-generator', category: 'text-tools', categoryName: 'Text Tools', icon: '📜', description: 'Generate placeholder Lorem Ipsum text for design and development.', keywords: ['lorem', 'ipsum', 'placeholder', 'text'] },

    // ===== STUDENT TOOLS =====
    { id: 'percentage-calculator', name: 'Percentage Calculator', slug: 'percentage-calculator', category: 'calculator-tools', categoryName: 'Student Tools', icon: '📊', description: 'Calculate percentages, percentage change, and more with ease.', keywords: ['percentage', 'calculate', 'math', 'percent'] },
    { id: 'cgpa-calculator', name: 'CGPA Calculator', slug: 'cgpa-calculator', category: 'calculator-tools', categoryName: 'Student Tools', icon: '🎓', description: 'Calculate your Cumulative Grade Point Average (CGPA) quickly.', keywords: ['cgpa', 'grade', 'gpa', 'calculate'] },
    { id: 'age-calculator', name: 'Age Calculator', slug: 'age-calculator', category: 'calculator-tools', categoryName: 'Student Tools', icon: '🎂', description: 'Calculate your exact age in years, months, and days from your birthdate.', keywords: ['age', 'birthday', 'calculate', 'date'] },
    { id: 'unit-converter', name: 'Unit Converter', slug: 'unit-converter', category: 'calculator-tools', categoryName: 'Student Tools', icon: '⚖️', description: 'Convert between units of length, weight, temperature, and more.', keywords: ['unit', 'convert', 'length', 'weight'] },
    { id: 'gpa-calculator', name: 'GPA Calculator', slug: 'gpa-calculator', category: 'calculator-tools', categoryName: 'Student Tools', icon: '📈', description: 'Calculate your Grade Point Average (GPA) with customizable grading scales.', keywords: ['gpa', 'grade', 'point', 'calculate'] },
    { id: 'password-generator', name: 'Password Generator', slug: 'password-generator', category: 'calculator-tools', categoryName: 'Student Tools', icon: '🔒', description: 'Generate strong, secure passwords with customizable options.', keywords: ['password', 'generate', 'secure', 'random'] },
    { id: 'aspect-ratio-calculator', name: 'Aspect Ratio Calculator', slug: 'aspect-ratio-calculator', category: 'calculator-tools', categoryName: 'Student Tools', icon: '📐', description: 'Calculate aspect ratios, resize dimensions proportionally, and find common resolutions.', keywords: ['aspect', 'ratio', 'resize', 'scale', 'dimensions'] },

    // ===== AUDIO TOOLS =====
    { id: 'audio-converter', name: 'Audio Converter', slug: 'audio-converter', category: 'audio-tools', categoryName: 'Audio Tools', icon: '🎵', description: 'Convert audio files between MP3, WAV, FLAC, AAC, and OGG formats. Free batch conversion.', keywords: ['audio', 'convert', 'mp3', 'wav', 'flac', 'aac', 'ogg', 'format'] },
    { id: 'audio-compressor', name: 'Audio Compressor', slug: 'audio-compressor', category: 'audio-tools', categoryName: 'Audio Tools', icon: '🗜️', description: 'Compress audio files to reduce size while maintaining quality. Perfect for sharing and streaming.', keywords: ['audio', 'compress', 'reduce', 'mp3', 'size'] },
    { id: 'audio-joiner', name: 'Audio Joiner', slug: 'audio-joiner', category: 'audio-tools', categoryName: 'Audio Tools', icon: '🔗', description: 'Merge multiple audio files into one. Combine songs, podcasts, or recordings seamlessly.', keywords: ['audio', 'join', 'merge', 'combine', 'mix'] },
    { id: 'audio-cutter', name: 'Audio Cutter', slug: 'audio-cutter', category: 'audio-tools', categoryName: 'Audio Tools', icon: '✂️', description: 'Cut and trim audio files with precision. Extract specific portions from songs or recordings.', keywords: ['audio', 'cut', 'trim', 'split', 'extract'] },
    { id: 'volume-booster', name: 'Volume Booster', slug: 'volume-booster', category: 'audio-tools', categoryName: 'Audio Tools', icon: '🔊', description: 'Increase audio volume and normalize sound levels. Make quiet audio louder.', keywords: ['volume', 'boost', 'normalize', 'amplify', 'loudness'] },
    { id: 'audio-speed-changer', name: 'Audio Speed Changer', slug: 'audio-speed-changer', category: 'audio-tools', categoryName: 'Audio Tools', icon: '⏩', description: 'Change audio playback speed without affecting pitch. Speed up or slow down audio files.', keywords: ['speed', 'tempo', 'pitch', 'slow', 'fast'] },
    { id: 'voice-recorder', name: 'Voice Recorder', slug: 'voice-recorder', category: 'audio-tools', categoryName: 'Audio Tools', icon: '🎤', description: 'Record voice directly in browser. Download recordings as MP3 or WAV files.', keywords: ['voice', 'record', 'audio', 'microphone', 'recording'] },
    { id: 'audio-to-text', name: 'Audio to Text', slug: 'audio-to-text', category: 'audio-tools', categoryName: 'Audio Tools', icon: '📝', description: 'Transcribe audio files to text. Convert speech to text automatically.', keywords: ['audio', 'text', 'transcribe', 'speech', 'convert'] },

    // ===== VIDEO TOOLS =====
    { id: 'video-converter', name: 'Video Converter', slug: 'video-converter', category: 'video-tools', categoryName: 'Video Tools', icon: '🎬', description: 'Convert videos between MP4, AVI, MOV, WMV, and WebM formats. Free batch conversion.', keywords: ['video', 'convert', 'mp4', 'avi', 'mov', 'wmv', 'webm', 'format'] },
    { id: 'video-compressor', name: 'Video Compressor', slug: 'video-compressor', category: 'video-tools', categoryName: 'Video Tools', icon: '📦', description: 'Compress video files to reduce size for sharing and streaming. Maintain quality.', keywords: ['video', 'compress', 'reduce', 'size', 'optimize'] },
    { id: 'video-cutter', name: 'Video Cutter', slug: 'video-cutter', category: 'video-tools', categoryName: 'Video Tools', icon: '✂️', description: 'Cut and trim videos with frame-accurate precision. Extract clips from longer videos.', keywords: ['video', 'cut', 'trim', 'clip', 'extract'] },
    { id: 'video-joiner', name: 'Video Joiner', slug: 'video-joiner', category: 'video-tools', categoryName: 'Video Tools', icon: '🔗', description: 'Merge multiple video files into one. Combine clips seamlessly without quality loss.', keywords: ['video', 'join', 'merge', 'combine', 'concatenate'] },
    { id: 'video-to-gif', name: 'Video to GIF Converter', slug: 'video-to-gif', category: 'video-tools', categoryName: 'Video Tools', icon: '🎞️', description: 'Convert video clips to animated GIFs. Create shareable GIFs from any video.', keywords: ['video', 'gif', 'convert', 'animate', 'animation'] },
    { id: 'video-resizer', name: 'Video Resizer', slug: 'video-resizer', category: 'video-tools', categoryName: 'Video Tools', icon: '📐', description: 'Resize videos for social media platforms. Optimize for Instagram, TikTok, YouTube.', keywords: ['video', 'resize', 'scale', 'dimensions', 'social media'] },
    { id: 'video-rotator', name: 'Video Rotator', slug: 'video-rotator', category: 'video-tools', categoryName: 'Video Tools', icon: '🔄', description: 'Rotate videos by 90°, 180°, or 270°. Fix orientation of recorded videos.', keywords: ['video', 'rotate', 'orientation', 'flip', 'turn'] },
    { id: 'video-thumbnail-extractor', name: 'Video Thumbnail Extractor', slug: 'video-thumbnail-extractor', category: 'video-tools', categoryName: 'Video Tools', icon: '🖼️', description: 'Extract thumbnail images from videos. Capture frames at any timestamp.', keywords: ['video', 'thumbnail', 'extract', 'frame', 'screenshot'] },
    { id: 'screen-recorder', name: 'Screen Recorder', slug: 'screen-recorder', category: 'video-tools', categoryName: 'Video Tools', icon: '🖥️', description: 'Record your screen with audio. Create tutorials, demos, and presentations.', keywords: ['screen', 'record', 'capture', 'video', 'tutorial'] },

    // ===== DESIGN TOOLS =====
    { id: 'color-palette-generator', name: 'Color Palette Generator', slug: 'color-palette-generator', category: 'design-tools', categoryName: 'Design Tools', icon: '🎨', description: 'Generate beautiful color palettes for your designs. Export to CSS, SCSS, or image.', keywords: ['color', 'palette', 'generate', 'scheme', 'design'] },
    { id: 'gradient-generator', name: 'Gradient Generator', slug: 'gradient-generator', category: 'design-tools', categoryName: 'Design Tools', icon: '🌈', description: 'Create stunning CSS gradients. Customize colors, direction, and export code.', keywords: ['gradient', 'css', 'generate', 'background', 'design'] },
    { id: 'font-pairing', name: 'Font Pairing Tool', slug: 'font-pairing', category: 'design-tools', categoryName: 'Design Tools', icon: '🔤', description: 'Find perfect font combinations for your designs. Preview Google Fonts pairings.', keywords: ['font', 'pairing', 'typography', 'google', 'design'] },
    { id: 'mockup-generator', name: 'Mockup Generator', slug: 'mockup-generator', category: 'design-tools', categoryName: 'Design Tools', icon: '📱', description: 'Create device mockups for your designs. iPhone, iPad, laptop, and more.', keywords: ['mockup', 'device', 'frame', 'presentation', 'design'] },
    { id: 'image-background-remover', name: 'Background Remover', slug: 'image-background-remover', category: 'design-tools', categoryName: 'Design Tools', icon: '🖼️', description: 'Remove backgrounds from images automatically. Get transparent PNGs instantly.', keywords: ['background', 'remove', 'transparent', 'png', 'cutout'] },
    { id: 'svg-optimizer', name: 'SVG Optimizer', slug: 'svg-optimizer', category: 'design-tools', categoryName: 'Design Tools', icon: '✨', description: 'Optimize and compress SVG files. Reduce file size without quality loss.', keywords: ['svg', 'optimize', 'compress', 'vector', 'icon'] },
    { id: 'favicon-generator', name: 'Favicon Generator', slug: 'favicon-generator', category: 'design-tools', categoryName: 'Design Tools', icon: '🔖', description: 'Generate favicons for your website. Create all sizes from one image.', keywords: ['favicon', 'icon', 'website', 'browser', 'generate'] },
    { id: 'social-media-image-resizer', name: 'Social Media Image Resizer', slug: 'social-media-image-resizer', category: 'design-tools', categoryName: 'Design Tools', icon: '📱', description: 'Resize images for all social media platforms. Instagram, Facebook, Twitter, LinkedIn presets.', keywords: ['social', 'media', 'resize', 'instagram', 'facebook', 'twitter'] },

    // ===== FINANCE TOOLS =====
    { id: 'loan-calculator', name: 'Loan Calculator', slug: 'loan-calculator', category: 'finance-tools', categoryName: 'Finance Tools', icon: '💰', description: 'Calculate loan payments, interest, and amortization schedule. Plan your finances.', keywords: ['loan', 'calculator', 'payment', 'interest', 'mortgage'] },
    { id: 'currency-converter', name: 'Currency Converter', slug: 'currency-converter', category: 'finance-tools', categoryName: 'Finance Tools', icon: '💱', description: 'Convert currencies with live exchange rates. Support for 150+ currencies worldwide.', keywords: ['currency', 'convert', 'exchange', 'rate', 'forex'] },
    { id: 'tip-calculator', name: 'Tip Calculator', slug: 'tip-calculator', category: 'finance-tools', categoryName: 'Finance Tools', icon: '💵', description: 'Calculate tips and split bills among friends. Quick and easy bill splitting.', keywords: ['tip', 'calculator', 'bill', 'split', 'gratuity'] },
    { id: 'budget-planner', name: 'Budget Planner', slug: 'budget-planner', category: 'finance-tools', categoryName: 'Finance Tools', icon: '📊', description: 'Plan and track your monthly budget. Manage income and expenses effectively.', keywords: ['budget', 'plan', 'expense', 'income', 'finance'] },
    { id: 'savings-calculator', name: 'Savings Calculator', slug: 'savings-calculator', category: 'finance-tools', categoryName: 'Finance Tools', icon: '🏦', description: 'Calculate savings growth with compound interest. Plan your financial goals.', keywords: ['savings', 'calculator', 'compound', 'interest', 'investment'] },
    { id: 'retirement-calculator', name: 'Retirement Calculator', slug: 'retirement-calculator', category: 'finance-tools', categoryName: 'Finance Tools', icon: '👴', description: 'Plan for retirement. Calculate how much you need to save for a comfortable retirement.', keywords: ['retirement', 'calculator', 'pension', '401k', 'planning'] },
    { id: 'gst-calculator', name: 'GST Calculator', slug: 'gst-calculator', category: 'finance-tools', categoryName: 'Finance Tools', icon: '🧾', description: 'Calculate GST (Goods and Services Tax) for any amount. Add or remove GST easily.', keywords: ['gst', 'tax', 'calculator', 'vat', 'sales'] },
    { id: 'discount-calculator', name: 'Discount Calculator', slug: 'discount-calculator', category: 'finance-tools', categoryName: 'Finance Tools', icon: '🏷️', description: 'Calculate final price after discounts and sales. Find out how much you save.', keywords: ['discount', 'sale', 'calculator', 'price', 'savings'] },

    // ===== HEALTH TOOLS =====
    { id: 'bmi-calculator', name: 'BMI Calculator', slug: 'bmi-calculator', category: 'health-tools', categoryName: 'Health Tools', icon: '⚖️', description: 'Calculate Body Mass Index (BMI). Check if you\'re in a healthy weight range.', keywords: ['bmi', 'calculator', 'weight', 'health', 'body'] },
    { id: 'calorie-calculator', name: 'Calorie Calculator', slug: 'calorie-calculator', category: 'health-tools', categoryName: 'Health Tools', icon: '🔥', description: 'Calculate daily calorie needs for weight loss, maintenance, or gain.', keywords: ['calorie', 'calculator', 'diet', 'weight', 'nutrition'] },
    { id: 'water-intake-calculator', name: 'Water Intake Calculator', slug: 'water-intake-calculator', category: 'health-tools', categoryName: 'Health Tools', icon: '💧', description: 'Calculate your daily water intake needs based on weight and activity level.', keywords: ['water', 'hydration', 'intake', 'health', 'drink'] },
    { id: 'heart-rate-calculator', name: 'Heart Rate Calculator', slug: 'heart-rate-calculator', category: 'health-tools', categoryName: 'Health Tools', icon: '❤️', description: 'Calculate target heart rate zones for exercise and training.', keywords: ['heart', 'rate', 'pulse', 'exercise', 'fitness'] },
    { id: 'sleep-calculator', name: 'Sleep Calculator', slug: 'sleep-calculator', category: 'health-tools', categoryName: 'Health Tools', icon: '😴', description: 'Calculate optimal sleep times. Wake up refreshed with proper sleep cycles.', keywords: ['sleep', 'calculator', 'rest', 'wake', 'cycle'] },
    { id: 'pregnancy-due-date-calculator', name: 'Pregnancy Due Date Calculator', slug: 'pregnancy-due-date-calculator', category: 'health-tools', categoryName: 'Health Tools', icon: '🤰', description: 'Calculate estimated due date for pregnancy. Track your pregnancy timeline.', keywords: ['pregnancy', 'due', 'date', 'baby', 'calculator'] },
    { id: 'body-fat-calculator', name: 'Body Fat Calculator', slug: 'body-fat-calculator', category: 'health-tools', categoryName: 'Health Tools', icon: '📏', description: 'Estimate body fat percentage using body measurements. Track fitness progress.', keywords: ['body', 'fat', 'percentage', 'fitness', 'health'] },
    { id: 'running-pace-calculator', name: 'Running Pace Calculator', slug: 'running-pace-calculator', category: 'health-tools', categoryName: 'Health Tools', icon: '🏃', description: 'Calculate running pace, speed, and finish time. Plan your race strategy.', keywords: ['running', 'pace', 'calculator', 'speed', 'race'] },
];

export const categories = [
    { id: 'image-tools', name: 'Image Tools', slug: 'image-tools', icon: '🖼️', color: 'bg-gradient-to-br from-rose-100 to-pink-100 text-rose-600 dark:from-rose-500/20 dark:to-pink-500/20 dark:text-rose-400', description: 'Powerful image editing tools — compress, resize, convert, and crop images online for free.' },
    { id: 'pdf-tools', name: 'PDF Tools', slug: 'pdf-tools', icon: '📄', color: 'bg-gradient-to-br from-orange-100 to-amber-100 text-orange-600 dark:from-orange-500/20 dark:to-amber-500/20 dark:text-orange-400', description: 'Complete PDF toolkit — merge, split, compress, and convert PDF files online.' },
    { id: 'developer-tools', name: 'Developer Tools', slug: 'developer-tools', icon: '💻', color: 'bg-gradient-to-br from-slate-100 to-gray-100 text-slate-600 dark:from-slate-500/20 dark:to-gray-500/20 dark:text-slate-400', description: 'Essential developer utilities — format JSON, test regex, decode JWT, and beautify code.' },
    { id: 'text-tools', name: 'Text & SEO Tools', slug: 'text-tools', icon: '📝', color: 'bg-gradient-to-br from-sky-100 to-blue-100 text-sky-600 dark:from-sky-500/20 dark:to-blue-500/20 dark:text-sky-400', description: 'Text processing and SEO tools — count words, generate slugs, create meta tags.' },
    { id: 'calculator-tools', name: 'Student Tools', slug: 'calculator-tools', icon: '🎓', color: 'bg-gradient-to-br from-lime-100 to-green-100 text-lime-600 dark:from-lime-500/20 dark:to-green-500/20 dark:text-lime-400', description: 'Student calculators and utilities — CGPA, GPA, age calculator, unit converter, and more.' },
    { id: 'audio-tools', name: 'Audio Tools', slug: 'audio-tools', icon: '🎵', color: 'bg-gradient-to-br from-cyan-100 to-teal-100 text-cyan-600 dark:from-cyan-500/20 dark:to-teal-500/20 dark:text-cyan-400', description: 'Audio editing and conversion tools — convert, compress, cut, and join audio files online.' },
    { id: 'video-tools', name: 'Video Tools', slug: 'video-tools', icon: '🎬', color: 'bg-gradient-to-br from-red-100 to-rose-100 text-red-600 dark:from-red-500/20 dark:to-rose-500/20 dark:text-red-400', description: 'Video editing toolkit — convert, compress, cut, and merge videos. Create GIFs and record screens.' },
    { id: 'design-tools', name: 'Design Tools', slug: 'design-tools', icon: '🎨', color: 'bg-gradient-to-br from-fuchsia-100 to-purple-100 text-fuchsia-600 dark:from-fuchsia-500/20 dark:to-purple-500/20 dark:text-fuchsia-400', description: 'Creative design tools — color palettes, gradients, fonts, mockups, and background removal.' },
    { id: 'finance-tools', name: 'Finance Tools', slug: 'finance-tools', icon: '💰', color: 'bg-gradient-to-br from-emerald-100 to-lime-100 text-emerald-600 dark:from-emerald-500/20 dark:to-lime-500/20 dark:text-emerald-400', description: 'Financial calculators — loan, currency, tips, budget, savings, and retirement planning.' },
    { id: 'health-tools', name: 'Health & Fitness Tools', slug: 'health-tools', icon: '❤️', color: 'bg-gradient-to-br from-rose-100 to-red-100 text-rose-600 dark:from-rose-500/20 dark:to-red-500/20 dark:text-rose-400', description: 'Health and fitness calculators — BMI, calories, heart rate, sleep, and workout planning.' },
];

export const getToolsByCategory = (categorySlug) => toolsData.filter(t => t.category === categorySlug);
export const getToolBySlug = (slug) => toolsData.find(t => t.slug === slug);
export const getCategoryBySlug = (slug) => categories.find(c => c.slug === slug);
export const searchTools = (query) => {
    const q = query.toLowerCase();
    return toolsData.filter(t =>
        t.name.toLowerCase().includes(q) ||
        t.description.toLowerCase().includes(q) ||
        t.keywords.some(k => k.includes(q))
    );
};
export const getRelatedTools = (toolSlug, limit = 4) => {
    const tool = getToolBySlug(toolSlug);
    if (!tool) return [];
    return toolsData.filter(t => t.category === tool.category && t.slug !== toolSlug).slice(0, limit);
};
export const popularTools = ['json-formatter', 'image-compressor', 'word-counter', 'merge-pdf', 'password-generator', 'age-calculator', 'base64-encoder-decoder', 'percentage-calculator'];

export default toolsData;
